/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'studentId' : string,
  'balance' : number,
  'accountNumber' : string,
}
export interface BankDetail {
  'id' : string,
  'branch' : string,
  'accountId' : string,
  'icon' : string,
  'bankName' : string,
}
export interface Student {
  'id' : string,
  'age' : bigint,
  'gpa' : number,
  'name' : string,
}
export interface Transaction {
  'id' : string,
  'accountId' : string,
  'date' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<[string, number, string], Account>,
  'createBankDetail' : ActorMethod<
    [string, string, string, string],
    BankDetail
  >,
  'createStudent' : ActorMethod<[string, bigint, number], Student>,
  'createTransaction' : ActorMethod<[number, string, string], Transaction>,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteBankDetail' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getAccount' : ActorMethod<[string], Account>,
  'getAccountsByStudent' : ActorMethod<[string], Array<Account>>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBankDetails' : ActorMethod<[], Array<BankDetail>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBankDetail' : ActorMethod<[string], BankDetail>,
  'getBankDetailsByAccount' : ActorMethod<[string], Array<BankDetail>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[string], Student>,
  'getTransaction' : ActorMethod<[string], Transaction>,
  'getTransactionsByAccount' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAccount' : ActorMethod<[string, string, number, string], Account>,
  'updateBankDetail' : ActorMethod<
    [string, string, string, string, string],
    BankDetail
  >,
  'updateStudent' : ActorMethod<[string, string, bigint, number], Student>,
  'updateTransaction' : ActorMethod<
    [string, number, string, string],
    Transaction
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];