/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'studentName' : string,
  'ifscCode' : string,
  'bankName' : string,
  'initialAmount' : number,
  'accountNumber' : string,
  'transactions' : Array<Transaction>,
  'studentClass' : string,
}
export interface BankDetail {
  'id' : string,
  'ifscCode' : string,
  'bankName' : string,
  'district' : string,
  'taluka' : string,
}
export interface Student {
  'id' : string,
  'dateOfBirth' : string,
  'name' : string,
  'district' : string,
  'taluka' : string,
  'accounts' : Array<Account>,
  'rollNumber' : string,
  'transactions' : Array<Transaction>,
  'studentClass' : string,
  'schoolName' : string,
}
export interface Transaction {
  'id' : string,
  'transactionType' : TransactionType,
  'studentName' : string,
  'date' : string,
  'totalAmount' : number,
  'initialAmount' : number,
  'accountNumber' : string,
  'amount' : number,
  'reason' : string,
}
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface UserProfile { 'name' : string, 'accountNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<
    [string, string, string, string, number, string],
    Account
  >,
  'createBankDetail' : ActorMethod<
    [string, string, string, string],
    BankDetail
  >,
  'createStudent' : ActorMethod<
    [string, string, string, string, string, string, string],
    Student
  >,
  'createTransaction' : ActorMethod<
    [string, string, number, string, TransactionType, number, string, number],
    Transaction
  >,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteBankDetail' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string], undefined>,
  'getAccount' : ActorMethod<[string], Account>,
  'getAccountsByStudent' : ActorMethod<[string], Array<Account>>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBankDetails' : ActorMethod<[], Array<BankDetail>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBankDetail' : ActorMethod<[string], BankDetail>,
  'getBankDetailsByDistrict' : ActorMethod<[string], Array<BankDetail>>,
  'getBankDetailsByTaluka' : ActorMethod<[string], Array<BankDetail>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPassbook' : ActorMethod<[string], [Account, Array<Transaction>]>,
  'getStudent' : ActorMethod<[string], Student>,
  'getTransaction' : ActorMethod<[string], Transaction>,
  'getTransactionsByAccount' : ActorMethod<[string], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTransactions' : ActorMethod<
    [string, string, string],
    {
      'studentName' : string,
      'ifscCode' : string,
      'bankName' : string,
      'transactions' : Array<Transaction>,
    }
  >,
  'updateAccount' : ActorMethod<
    [string, string, string, string, string, number, string],
    Account
  >,
  'updateBankDetail' : ActorMethod<
    [string, string, string, string, string],
    BankDetail
  >,
  'updateStudent' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    Student
  >,
  'updateTransaction' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      string,
      TransactionType,
      number,
      string,
      number,
    ],
    Transaction
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];