/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'balance' : IDL.Float64,
  'accountNumber' : IDL.Text,
});
export const BankDetail = IDL.Record({
  'id' : IDL.Text,
  'branch' : IDL.Text,
  'accountId' : IDL.Text,
  'icon' : IDL.Text,
  'bankName' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'gpa' : IDL.Float64,
  'name' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'accountId' : IDL.Text,
  'date' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [Account], []),
  'createBankDetail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BankDetail],
      [],
    ),
  'createStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [Student], []),
  'createTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [Transaction],
      [],
    ),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'deleteBankDetail' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [], []),
  'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
  'getAccountsByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Account)], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBankDetail' : IDL.Func([IDL.Text], [BankDetail], ['query']),
  'getBankDetailsByAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BankDetail)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
  'getTransactionsByAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Account],
      [],
    ),
  'updateBankDetail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BankDetail],
      [],
    ),
  'updateStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [Student],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [Transaction],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'balance' : IDL.Float64,
    'accountNumber' : IDL.Text,
  });
  const BankDetail = IDL.Record({
    'id' : IDL.Text,
    'branch' : IDL.Text,
    'accountId' : IDL.Text,
    'icon' : IDL.Text,
    'bankName' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'gpa' : IDL.Float64,
    'name' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'accountId' : IDL.Text,
    'date' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [Account],
        [],
      ),
    'createBankDetail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BankDetail],
        [],
      ),
    'createStudent' : IDL.Func([IDL.Text, IDL.Nat, IDL.Float64], [Student], []),
    'createTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [Transaction],
        [],
      ),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'deleteBankDetail' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [], []),
    'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
    'getAccountsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Account)],
        ['query'],
      ),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBankDetail' : IDL.Func([IDL.Text], [BankDetail], ['query']),
    'getBankDetailsByAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BankDetail)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
    'getTransactionsByAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Account],
        [],
      ),
    'updateBankDetail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BankDetail],
        [],
      ),
    'updateStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [Student],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [Transaction],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };